spring:
  application:
    name: pretemoica
  datasource:
    url: jdbc:postgresql://localhost:5432/projetPret
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update



